export default [
  { value: 'Alexandra Hospital', label: 'Alexandra Hospital' },
  { value: 'Ang Mo Kio - Thye Hua Kwan Hospital', label: 'Ang Mo Kio - Thye Hua Kwan Hospital' },
  { value: 'Ang Mo Kio Polyclinic', label: 'Ang Mo Kio Polyclinic' },
  { value: 'Bedok Polyclinic', label: 'Bedok Polyclinic' },
  { value: 'Bright Vision Hospital', label: 'Bright Vision Hospital' },
  { value: 'Bukit Batok Polyclinic', label: 'Bukit Batok Polyclinic' },
  { value: 'Bukit Merah Polyclinic', label: 'Bukit Merah Polyclinic' },
  { value: 'Changi General Hospital', label: 'Changi General Hospital' },
  { value: 'Choa Chu Kang Polyclinic', label: 'Choa Chu Kang Polyclinic' },
  { value: 'Clementi Polyclinic', label: 'Clementi Polyclinic' },
  { value: 'Farrer Park Hospital', label: 'Farrer Park Hospital' },
  { value: 'Geylang Polyclinic', label: 'Geylang Polyclinic' },
  { value: 'Gleneagles Hospital', label: 'Gleneagles Hospital' },
  { value: 'Hougang Polyclinic', label: 'Hougang Polyclinic' },
  { value: 'Institute of Mental Health', label: 'Institute of Mental Health' },
  { value: 'Jurong Community Hospital', label: 'Jurong Community Hospital' },
  { value: 'Jurong Polyclinic', label: 'Jurong Polyclinic' },
  { value: 'Khoo Teck Puat Hospital', label: 'Khoo Teck Puat Hospital' },
  { value: 'KK Women\'s and Children\'s Hospital', label: 'KK Women\'s and Children\'s Hospital' },
  { value: 'Marine Parade Polyclinic', label: 'Marine Parade Polyclinic' },
  { value: 'Mount Alvernia Hospital', label: 'Mount Alvernia Hospital' },
  { value: 'Mount Elizabeth Hospital', label: 'Mount Elizabeth Hospital' },
  { value: 'Mount Elizabeth Novena Hospital', label: 'Mount Elizabeth Novena Hospital' },
  { value: 'National Heart Centre', label: 'National Heart Centre' },
  { value: 'National University Hospital', label: 'National University Hospital' },
  { value: 'Ng Teng Fong General Hospital', label: 'Ng Teng Fong General Hospital' },
  { value: 'Outram Community Hospital', label: 'Outram Community Hospital' },
  { value: 'Outram Polyclinic', label: 'Outram Polyclinic' },
  { value: 'Parkway East Hospital', label: 'Parkway East Hospital' },
  { value: 'Pasir Ris Polyclinic', label: 'Pasir Ris Polyclinic' },
  { value: 'Queenstown Polyclinic', label: 'Queenstown Polyclinic' },
  { value: 'Raffles Hospital', label: 'Raffles Hospital' },
  { value: 'Ren Ci Community Hospital', label: 'Ren Ci Community Hospital' },
  { value: 'Sengkang Community Hospital', label: 'Sengkang Community Hospital' },
  { value: 'Sengkang General Hospital', label: 'Sengkang General Hospital' },
  { value: 'Sengkang Polyclinic', label: 'Sengkang Polyclinic' },
  { value: 'Singapore General Hospital', label: 'Singapore General Hospital' },
  { value: 'St Andrew\'s Community Hospital', label: 'St Andrew\'s Community Hospital' },
  { value: 'St Andrew\'s Community Hospital', label: 'St Andrew\'s Community Hospital' },
  { value: 'St Luke\'s Hospital', label: 'St Luke\'s Hospital' },
  { value: 'Tampines Polyclinic', label: 'Tampines Polyclinic' },
  { value: 'Tan Tock Seng Hospital', label: 'Tan Tock Seng Hospital' },
  { value: 'Thomson Medical Centre', label: 'Thomson Medical Centre' },
  { value: 'Toa Payoh Polyclinic', label: 'Toa Payoh Polyclinic' },
  { value: 'Woodlands Polyclinic', label: 'Woodlands Polyclinic' },
  { value: 'Yishun Community Hospital', label: 'Yishun Community Hospital' },
  { value: 'Yishun Polyclinic', label: 'Yishun Polyclinic' },
];
