const departments = [
  'Cadiology',
  'Dermatology',
  'Dental',
  'Diagnostic Radiology',
  'Ear, Nose and Throat',
  'Emergency Medicine',
  'Endocrinology',
  'Family Medicine',
  'Infectious Diseases',
  'Internal Medicine',
  'Gastroenterology',
  'General Medicine',
  'Geriatric Medicine',
  'Gynecology',
  'Hematology',
  'Neurology',
  'Ophthalmology',
  'Pathology',
  'Pain Medicine',
  'Palliative Medicine',
  'Pediatrics',
  'Physiotherapy',
  'Psychiatry',
  'Occupational Therapy',
  'Oncology',
  'Ophthalmology',
  'Orthopedic',
  'Renal Medicine',
  'Urology',
  'Vascular and Interventional Radiology'
];

module.exports = departments;