const hospitals = [
  'Alexandra Hospital',
  'Ang Mo Kio - Thye Hua Kwan Hospital',
  'Ang Mo Kio Polyclinic',
  'Bedok Polyclinic',
  'Bright Vision Hospital', 
  'Bukit Batok Polyclinic',
  'Bukit Merah Polyclinic',
  'Changi General Hospital',
  'Choa Chu Kang Polyclinic',
  'Clementi Polyclinic',
  'Farrer Park Hospital',
  'Geylang Polyclinic',
  'Gleneagles Hospital',
  'Hougang Polyclinic',
  'Institute of Mental Health',
  'Jurong Community Hospital',
  'Jurong Polyclinic',
  'Khoo Teck Puat Hospital',
  'KK Women\'s and Children\'s Hospital',
  'Marine Parade Polyclinic',
  'Mount Alvernia Hospital',
  'Mount Elizabeth Hospital',
  'Mount Elizabeth Novena Hospital',
  'National Heart Centre',
  'National University Hospital',
  'Ng Teng Fong General Hospital',
  'Outram Community Hospital',
  'Outram Polyclinic',
  'Parkway East Hospital',
  'Pasir Ris Polyclinic',
  'Queenstown Polyclinic',
  'Raffles Hospital',
  'Ren Ci Community Hospital',
  'Sengkang Community Hospital',
  'Sengkang General Hospital',
  'Sengkang Polyclinic',
  'Singapore General Hospital',
  'St Andrew\'s Community Hospital',
  'St Luke\'s Hospital',
  'Tampines Polyclinic',
  'Tan Tock Seng Hospital',
  'Thomson Medical Centre',
  'Toa Payoh Polyclinic',
  'Woodlands Polyclinic',
  'Yishun Community Hospital',
  'Yishun Polyclinic'
];

module.exports = hospitals;